import { AppFrame, Panel, Badge, Button, Avatar, SectionLabel } from "./_shared/ui";
import {
  TRANSCRIPT,
  SUMMARY_V1,
  REVIEWER_FEEDBACK,
  REFERENCED_SPAN,
} from "./_shared/mockData";
import { AlertTriangle, Quote, Sparkles, X } from "lucide-react";

export function ReviewWorkspace() {
  return (
    <AppFrame
      step={4}
      title="Review the summary"
      subtitle="Read the transcript against the AI summary, then tell OMNICON what to fix before regenerating."
      headerRight={
        <>
          <Badge tone="neutral">Granola</Badge>
          <Badge tone="neutral">Q3 Product Review</Badge>
          <Badge tone="accent">Claude 3.5 Sonnet</Badge>
        </>
      }
      footer={
        <span className="omni-mono text-[11px] text-[#5E6675]">
          V1 generated by Claude 3.5 Sonnet · 1,840 words
        </span>
      }
    >
      <div className="flex h-full min-h-0 gap-4">
        {/* LEFT — transcript / summary */}
        <Panel
          className="min-h-0 w-[58%]"
          bodyClassName="flex min-h-0 flex-col p-0"
        >
          {/* Segmented toggle */}
          <div className="shrink-0 border-b border-[#1B212D] px-4 py-3">
            <div className="inline-flex rounded-lg border border-[#2E3749] bg-[#0A0D13] p-1">
              <button className="rounded-md bg-[#5EEAD4] px-4 py-1.5 text-[12px] font-semibold text-[#06201C]">
                Transcript
              </button>
              <button className="rounded-md px-4 py-1.5 text-[12px] font-medium text-[#9AA4B5] hover:text-[#E6E9EF]">
                Summary
              </button>
            </div>
          </div>

          {/* Transcript list */}
          <div className="omni-scroll min-h-0 flex-1 overflow-y-auto px-4 py-3">
            <div className="flex flex-col gap-3">
              {TRANSCRIPT.map((seg) => (
                <div
                  key={seg.id}
                  className={
                    "rounded-lg border bg-[#12161F] p-3 " +
                    (seg.flagged
                      ? "border-[#232A38] border-l-2 border-l-[#FBBF24]"
                      : "border-[#1B212D]")
                  }
                >
                  <div className="flex items-start gap-3">
                    <Avatar initials={seg.initials} />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="text-[13px] font-semibold text-[#E6E9EF]">
                          {seg.speaker}
                        </span>
                        <span className="omni-mono text-[11px] text-[#5E6675]">
                          {seg.t}
                        </span>
                        {seg.flagged && (
                          <Badge tone="amber">
                            <AlertTriangle className="h-3 w-3" />
                            Needs review
                          </Badge>
                        )}
                      </div>
                      <p className="mt-1 text-[13px] leading-relaxed text-[#9AA4B5]">
                        {seg.text}
                      </p>
                      {seg.flagged && seg.flagReason && (
                        <p className="mt-1.5 text-[11px] text-[#FBBF24]">
                          {seg.flagReason}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Summary view markup (hidden / inactive) */}
            <div className="hidden">
              {SUMMARY_V1.map((section) => (
                <div key={section.heading}>
                  <SectionLabel>{section.heading}</SectionLabel>
                  <ul>
                    {section.bullets.map((b, i) => (
                      <li key={i}>{b}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </Panel>

        {/* RIGHT — feedback */}
        <Panel
          title="Your feedback"
          className="min-h-0 w-[42%]"
          bodyClassName="flex min-h-0 flex-col p-4"
        >
          <p className="text-[12px] leading-relaxed text-[#9AA4B5]">
            Describe the corrections OMNICON should apply when regenerating the
            summary.
          </p>

          <textarea
            defaultValue={REVIEWER_FEEDBACK}
            className="omni-scroll mt-3 min-h-[160px] w-full resize-none rounded-lg border border-[#2E3749] bg-[#0A0D13] p-3 text-[13px] leading-relaxed text-[#E6E9EF] outline-none focus:border-[#0F766E]"
          />

          <div className="mt-4">
            <SectionLabel>Referenced span (optional)</SectionLabel>
            <div className="rounded-lg border border-[#232A38] bg-[#0A0D13] p-3">
              <div className="flex items-start gap-2.5">
                <Quote className="mt-0.5 h-4 w-4 shrink-0 text-[#5EEAD4]" />
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[12px] font-semibold text-[#E6E9EF]">
                      {REFERENCED_SPAN.speaker}
                    </span>
                    <span className="omni-mono text-[11px] text-[#5E6675]">
                      {REFERENCED_SPAN.t}
                    </span>
                  </div>
                  <p className="mt-1 text-[12px] leading-relaxed text-[#9AA4B5]">
                    "{REFERENCED_SPAN.text}"
                  </p>
                </div>
                <button className="shrink-0 rounded p-0.5 text-[#5E6675] hover:text-[#E6E9EF]">
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          </div>

          <div className="mt-auto pt-4">
            <Button variant="primary" className="w-full">
              <Sparkles className="h-4 w-4" />
              Generate V2
            </Button>
          </div>
        </Panel>
      </div>
    </AppFrame>
  );
}
