// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/omnicon/ConversationPicker.tsx": () => import("../components/mockups/omnicon/ConversationPicker.tsx"),
  "./components/mockups/omnicon/DiffReview.tsx": () => import("../components/mockups/omnicon/DiffReview.tsx"),
  "./components/mockups/omnicon/ModelPicker.tsx": () => import("../components/mockups/omnicon/ModelPicker.tsx"),
  "./components/mockups/omnicon/OutputObservability.tsx": () => import("../components/mockups/omnicon/OutputObservability.tsx"),
  "./components/mockups/omnicon/ReviewWorkspace.tsx": () => import("../components/mockups/omnicon/ReviewWorkspace.tsx"),
  "./components/mockups/omnicon/SourcePicker.tsx": () => import("../components/mockups/omnicon/SourcePicker.tsx")
};
